package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.Admin;
import com.zc.loginserver.domain.entity.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    @Insert({
        "insert into t_admin (id, passwd, ",
        "nickname, phoneno)",
        "values (#{id,jdbcType=BIGINT}, #{passwd,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{phoneno,jdbcType=VARCHAR})"
    })
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);
}