package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.GroupUser;
import com.zc.loginserver.domain.entity.GroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int countByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int deleteByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    @Insert({
        "insert into t_group_user (id, userid, ",
        "groupid)",
        "values (#{id,jdbcType=BIGINT}, #{userid,jdbcType=BIGINT}, ",
        "#{groupid,jdbcType=BIGINT})"
    })
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int insertSelective(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    List<GroupUser> selectByExample(GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") GroupUser record, @Param("example") GroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExample(@Param("record") GroupUser record, @Param("example") GroupUserExample example);
}