package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.Group;
import com.zc.loginserver.domain.entity.GroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    @Insert({
        "insert into t_group (id, groupname)",
        "values (#{id,jdbcType=BIGINT}, #{groupname,jdbcType=VARCHAR})"
    })
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupExample example);
}