package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.SysPermissionRole;
import com.zc.loginserver.domain.entity.SysPermissionRoleExample;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int countByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int deleteByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    @Insert({
            "insert into sys_permission_role (id, role_id, ",
            "permission_id)",
            "values (#{id,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, ",
            "#{permissionId,jdbcType=BIGINT})"
    })
    int insert(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int insertSelective(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    List<SysPermissionRole> selectByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysPermissionRole record, @Param("example") SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExample(@Param("record") SysPermissionRole record, @Param("example") SysPermissionRoleExample example);
}