package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.SysPermission;
import com.zc.loginserver.domain.entity.SysPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

import javax.annotation.security.PermitAll;

public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int countByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int deleteByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    @Insert({
        "insert into sys_permission (id, name, ",
        "description, url, ",
        "pid)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=BIGINT})"
    })
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    List<SysPermission> selectByExample(SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExample(@Param("record") SysPermission record, @Param("example") SysPermissionExample example);


    List<SysPermission> findPermissionByUserId(@Param("id") Long id);

}