package com.zc.loginserver.domain.repository;

import com.zc.loginserver.domain.entity.SysRoleUser;
import com.zc.loginserver.domain.entity.SysRoleUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int countByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int deleteByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    @Insert({
            "insert into sys_role_user (id, sys_user_id, ",
            "sys_role_id)",
            "values (#{id,jdbcType=BIGINT}, #{sysUserId,jdbcType=BIGINT}, ",
            "#{sysRoleId,jdbcType=BIGINT})"
    })
    int insert(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int insertSelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    List<SysRoleUser> selectByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleUser record, @Param("example") SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbggenerated Tue Dec 25 16:42:45 CST 2018
     */
    int updateByExample(@Param("record") SysRoleUser record, @Param("example") SysRoleUserExample example);
}