package com.zc.loginserver.domain.entity;

public class GroupUser extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_user.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_user.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_user.groupid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long groupid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_user.id
     *
     * @return the value of t_group_user.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_user.id
     *
     * @param id the value for t_group_user.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_user.userid
     *
     * @return the value of t_group_user.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_user.userid
     *
     * @param userid the value for t_group_user.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_user.groupid
     *
     * @return the value of t_group_user.groupid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_user.groupid
     *
     * @param groupid the value for t_group_user.groupid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }
}