package com.zc.loginserver.domain.entity;

public class Group extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.groupname
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.id
     *
     * @return the value of t_group.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.id
     *
     * @param id the value for t_group.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.groupname
     *
     * @return the value of t_group.groupname
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.groupname
     *
     * @param groupname the value for t_group.groupname
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}