package com.zc.loginserver.domain.entity;

public class Role extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.descpt
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private String descpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.category
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role
     *
     * @return the value of t_role.role
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role
     *
     * @param role the value for t_role.role
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.descpt
     *
     * @return the value of t_role.descpt
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public String getDescpt() {
        return descpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.descpt
     *
     * @param descpt the value for t_role.descpt
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setDescpt(String descpt) {
        this.descpt = descpt == null ? null : descpt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.category
     *
     * @return the value of t_role.category
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.category
     *
     * @param category the value for t_role.category
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}