package com.zc.loginserver.domain.entity;

public class UserRole extends BaseDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.roleid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    private Long roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.userid
     *
     * @return the value of t_user_role.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.userid
     *
     * @param userid the value for t_user_role.userid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.roleid
     *
     * @return the value of t_user_role.roleid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.roleid
     *
     * @param roleid the value for t_user_role.roleid
     *
     * @mbggenerated Fri Dec 21 17:37:49 CST 2018
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}